// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_Demo_i(Fl_Button*, void*);
  static void cb_Demo(Fl_Button*, void*);
  void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
  void cb_Demo1_i(Fl_Button*, void*);
  static void cb_Demo1(Fl_Button*, void*);
  void cb_Save1_i(Fl_Button*, void*);
  static void cb_Save1(Fl_Button*, void*);
public:
  void show();
  void Demo_cb();
  void Save_cb();
  void StencilDemo_cb();
  void SaveStencil_cb();
};
#endif
