// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "gui.h"

void GUI::cb_Demo_i(Fl_Button*, void*) {
  Demo_cb();
}
void GUI::cb_Demo(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->user_data()))->cb_Demo_i(o,v);
}

void GUI::cb_Save_i(Fl_Button*, void*) {
  Save_cb();
}
void GUI::cb_Save(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->user_data()))->cb_Save_i(o,v);
}

void GUI::cb_Demo1_i(Fl_Button*, void*) {
  StencilDemo_cb();
}
void GUI::cb_Demo1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->user_data()))->cb_Demo1_i(o,v);
}

void GUI::cb_Save1_i(Fl_Button*, void*) {
  SaveStencil_cb();
}
void GUI::cb_Save1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->user_data()))->cb_Save1_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(351, 326, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 23, 335, 124, "Soft Shadow Mapping");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)16);
      o->selection_color(FL_INACTIVE_COLOR);
      o->labelfont(1);
      o->labelcolor((Fl_Color)4);
      { Fl_Button* o = new Fl_Button(56, 35, 225, 40, "Demo");
        o->labelfont(1);
        o->callback((Fl_Callback*)cb_Demo);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(56, 89, 225, 40, "Save");
        o->labelfont(1);
        o->callback((Fl_Callback*)cb_Save);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(5, 190, 335, 125, "Stencil Texture Mapping");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)16);
      o->labelfont(1);
      o->labelcolor((Fl_Color)4);
      { Fl_Button* o = new Fl_Button(56, 203, 225, 40, "Demo");
        o->labelfont(1);
        o->callback((Fl_Callback*)cb_Demo1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(56, 258, 225, 40, "Save");
        o->labelfont(1);
        o->callback((Fl_Callback*)cb_Save1);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::Demo_cb() {
  scene->Demo();
}

void GUI::Save_cb() {
  scene->Save();
}

void GUI::StencilDemo_cb() {
  scene->StencilDemo();
}

void GUI::SaveStencil_cb() {
  scene->SaveStencil();
}
